### ISSUE TITLE
First field can't start with comment prefix even if quoted

### ISSUE THREAD

**Issue by Anaphory** [cldf/csvw#13]
Reading the source code, it looks like checking for comment prefixes is done *after* the line has been parsed and un-quoted as a CSV line. This means that a line is interpreted as comment even if the comment prefix is quoted as part of the first field value of the line, which is probably not extended.

(This does not look easy to fix, unfortunately.)

**Comment by xrotwang** [comment]
This is now addressed in the [README](https://github.com/cldf/csvw/blob/master/README.md#known-limitations).
