### ISSUE TITLE
For DictReader: Empty dialect is not the default dialect

### ISSUE THREAD

**Issue by Anaphory** [cldf/csvw#14]
Due to the test
https://github.com/cldf/csvw/blob/29871bd79b37c829b5f542537b26014bb9c41161/src/csvw/dsv.py#L228
the `None`-dialect, which is the default argument for `UnicodeReader`, is different from the default dialect `Dialect()`, which does specify a non-empty default comment prefix and therefore *does* handle comment lines.

Is this behaving as intended?

**Comment by xrotwang** [comment]
Yes. Not specifying a dialect is supposed to be compatible with python std libs default csv reading behaviour.
