### ISSUE TITLE
Cannot pass Datatype to Column constructor

### ISSUE THREAD

**Issue by Anaphory** [cldf/csvw#17]
I just wanted to write the following code:
```
original_dataset.add_table(
        "cognatesets.csv",
        Column(name="Form_ID",
               datatype=original_dataset["FormTable", "id"].datatype),
        Column(name="Cognateset_ID",
               datatype="str"))
```

However, the constructor calls `Datatype.fromvalue`, which does not actually work when it is passed a `Datatype` object. (And that is correctly stated in the documentation, but it is unexpected.)
https://github.com/cldf/csvw/blob/c3a3b234d4f2f9580246a5c530a8cc0f19e8e281/src/csvw/metadata.py#L250

(If #3 was solved, I would not even have tried.)

**Comment by Anaphory** [comment]
The workaround is not hard: I just use

    original_dataset["FormTable", "id"].datatype.asdict()

instead. But it feels strange nonetheless.

**Comment by xrotwang** [comment]
I agree. Fixing this should also be fairly simple.
