### ISSUE TITLE
Consider adding _len_ method to `Table`

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/csvw#30]
It would be useful to have a `__len__` method on `Table` instances so this works:

```python
if len(cldf['LanguageTable']):
   print("we have languages!")
```

...but I guess this requires iterating over all rows to know, so it's expensive (unless you want to try load that from the metadata)

**Comment by xrotwang** [comment]
```python
if next(cldf['LanguageTable']):
    ...
```
should be cheap.

**Comment by SimonGreenhill** [comment]
btw -- next(cldf['table']) raises `TypeError: 'Table' object is not an iterator`, there's no `Table.__next__()`

**Comment by xrotwang** [comment]
Ah, so we should add that!

**Comment by xflr6** [comment]
I don't think we want to make the table an *exhaustable* iterator  (it is [already iterable](https://github.com/cldf/csvw/blob/1932e2bd0614912190f5ba076179cc0a69ec543c/src/csvw/metadata.py#L629-L630), AFAICT).

@xrotwang : maybe you meant `if next(iter(clds['LanguageTable'])):` above?

**Comment by xflr6** [comment]
For the use case at hand it might be enough to add `__bool__` so we can do `if cldf['LanguageTable']`

**Comment by xrotwang** [comment]
Ah, yes. That sounds better.

Sebastian Bank <notifications@github.com> schrieb am Fr., 31. Jan. 2020,
18:35:

**Comment by xrotwang** [comment]
Doing a bit more thinking, I'm now inclined to not add any method at all. Adding `__bool__` would break backwards compatibility (think of code like `pycldf.Dataset.add_table`) which returns a table but might also return `None` - and checking the result with `if table`. And the missing `__len__` method can be correctly interpreted as "that's hard (or expensive) to know".

Please re-open, if you disagree.
