### ISSUE TITLE
All columns specified in the metadata must be present/added when reading data rows

### ISSUE THREAD

**Issue by xrotwang** [cldf/csvw#40]
Since we already augment data rows with virtual columns when reading data, we should also add `None` values for all regular columns specified in the metadata.

See https://github.com/cldf/pycldf/issues/115

While we could also insist on each row containing sufficiently many values, the proposed behaviour seems more in line with what Python's dict reader does.

**Comment by Anaphory** [comment]
Sure! Conceptually, that's the kind of solution I would have suggested.
