### ISSUE TITLE
Should Dataset.write ignore columns it doesn't recognize?

### ISSUE THREAD

**Issue by Anaphory** [cldf/csvw#57]
When writing a table, the writer
https://github.com/cldf/csvw/blob/45584ad63ff3002a9b3a8073607c1847c5cbac58/src/csvw/metadata.py#L649-L652
ignores all columns not in the table schema. I have used this a few times, in particular in quick-and-dirty scripts to manipulate CLDF data, but I have also been sometimes confused about outputs (eg. due to typos in the column name), and it is also a deviation from the Python core `csv` behaviour. Is it a conscious choice here, or is this a thing that we should consider changing down the line, preferably before too many other places start relying on it?

**Comment by xrotwang** [comment]
@Anaphory ah, ok. I think now I understand. I'm not sure, I'd want to break backwards-compatibility for this, though. But something like a `strict=True` flag for `Table.write` would be ok. To make this usable from libraries like `pycldf`, these would need to be changed, too, of course.
