### ISSUE TITLE
Remove dependency on clldutils

### ISSUE THREAD

**Issue by xrotwang** [cldf/csvw#6]
Functionality of `clldutils` is still used in some places. These should be removed such that csvw 1.0 does not depend on `clldutils`:
- [ ] `clldutils.attrlib`: `asdict` and `valid_re` should be copied here.
- [ ] `clldutils.misc`: `lazyproperty` should be copied here, `normalize_name` should be moved here, i.e. be reomoved from `clldutils` as of v2.0
- [ ] `clldutils.path.move`: should be copied here.

**Comment by xflr6** [comment]
Removing `clldutils.misc.normalize_name` also requires removing then obsolete `clldutils.dsv` (`NamedTupleReader`) and `clldutils.csvw`. In `clldutils` 2.0, modules like `clldutils.iso_639_3` should then use this libary as a replacement.
