### ISSUE TITLE
CSVW mapping to RDF?

### ISSUE THREAD

**Issue by danbri** [cldf/csvw#71]
Will this work for using CSVW with mappings to RDF?

**Comment by xrotwang** [comment]
Not right now. Only [csv2json](https://www.w3.org/TR/csv2json/) is implemented.

**Comment by xrotwang** [comment]
I actually implemented `csv2json` mostly to be able to run the conformance test suite. The actual use cases for the library so far don't make use of this as far as I know.

**Comment by danbri** [comment]
Thanks!
