### ISSUE TITLE
 Installation Errors with csvw2json and csvwvalidate

### ISSUE THREAD

**Issue by megin1989** [cldf/csvw#75]
**When we attempt to run these commands in the command line, we encounter the following errors:**

 `╰─ $ csvw2json datapackage.json 
Command 'csvw2json' not found, did you mean:
  command 'csv2json' from deb node-d3-dsv (1.1.1-5)
Try: sudo apt install <deb name>

…  WSL  megin  ~  …  csv-sql-schema  csv-old  csvw                                                                                                             299ms   13:25:11 
╰─ $ csvwvalidate datapackage.json 
csvwvalidate: command not found

…  WSL  megin  ~  …  csv-sql-schema  csv-old  csvw                                                                                                             397ms   13:25:44 
╰─ $ sudo apt install csvw2json
[sudo] password for megin: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package csvw2json

…  WSL  megin  ~  …  csv-sql-schema  csv-old  csvw                                                                                                            4.672s   13:26:38 
╰─ $ which csvw2json

…  WSL  megin  ~  …  csv-sql-schema  csv-old  csvw                                                                                                               0ms   13:27:02 
╰─ $ `

**Comment by xrotwang** [comment]
Hm. `csvw2json` is supposed to be installed when the `csvw` package is installed, see https://github.com/cldf/csvw/blob/90ac48577a659cc435a5bd442a907781317f7547/setup.cfg#L59-L64
How did you install `csvw`?

**Comment by xrotwang** [comment]
Cannot confirm. Here's what happens when I install `csvw` in a fresh virtual environment (on Ubuntu):
```shell
$ pip install csvw
...
$ which csvw2json
/home/robert/venvs/testcsvw/bin/csvw2json
```

**Comment by LinguList** [comment]
I can confirm for a fresh venv with a windows operation system, after having run `python -m pip install csvw` that csvw2json is also installed / available.

**Comment by chrzyki** [comment]
Just speculating here but the problem might be the Windows Subsystem for Linux you appear to be running. Maybe the entry points are ill-defined for WSL after the package is installed? Can you call the entry points manually with something like `python -m csvw.__main__:csvw2json`?

**Comment by chrzyki** [comment]
> Checked in Linux system got the same error
> 
> sudo apt install csv2josn [sudo] password for megin: Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package csv2josn
> 
> Python version is 3.10.12

- There is a typo in `csv2josn` in your sample command.
- The command you seem to be looking for is `csvw2json`
- It is not installed via your systems package manager but provided by the `csvw` package, meaning you install the package and (depending on the configuration of your local environment) get the commanded provided by `csvw` in your `$PATH`:

```
$ python --version
Python 3.12.4
$ python -m venv venv
$ source venv/bin/activate
$ pip install csvw
$ which csvw2json 
/home/chrzyki/venv/bin/csvw2json
$  csvw2json
usage: csvw2json [-h] url
csvw2json: error: the following arguments are required: url
```

**Comment by megin1989** [comment]
Here's a revised version of your message:

"Thank you. It is working now. I received the message 'FAIL'. 

Should we print the error details here?"

**Comment by xrotwang** [comment]
> Should we print the error details here?

What command were you running?

**Comment by megin1989** [comment]
Should we print the validation error details, such as 'The required datatype of this field is Integer,' here?

**Comment by xrotwang** [comment]
> Should we print the validation error details, such as 'The required datatype of this field is Integer,' here?

This was the issue about installation problems - and as far as I can tell, these have been sorted out. So I'd rather close this issue.
