### ISSUE TITLE
Add usage instructions, please

### ISSUE THREAD

**Issue by bencomp** [cldf/csvw#9]
I found this repository through PyPI, but it's not clear to me if this is a library and/or command-line tool and if so, how to use it. Could you please add some basic usage instructions?

**Comment by bencomp** [comment]
Thanks, that was quick! :)

**Comment by xflr6** [comment]
Thanks, added some basic example. This library is used mainly to serve as backend for https://github.com/cldf/pycldf, see also http://cldf.clld.org/
